CC = gcc
CFLAGS = -Wall -g
LDFLAGS = -lrt

all: bt1 bt2 bt3

bt1: bt1.c
	$(CC) $(CFLAGS) bt1.c -o bt1 $(LDFLAGS)

bt2: bt2.c
	$(CC) $(CFLAGS) bt2.c -o bt2 $(LDFLAGS)

bt3: bt3.c
	$(CC) $(CFLAGS) bt3.c -o bt3 $(LDFLAGS)

clean:
	rm -f bt1 bt2 bt3